// Code generated by goagen v1.1.0, DO NOT EDIT.
//
// API "todo": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/meier-christoph/todo-backend-golang-goa/design
// --out=$(GOPATH)/src/github.com/meier-christoph/todo-backend-golang-goa
// --version=v1.1.0-dirty

package app
