// Code generated by goagen v1.1.0, DO NOT EDIT.
//
// API "todo": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/meier-christoph/todo-backend-golang-goa/design
// --out=$(GOPATH)/src/github.com/meier-christoph/todo-backend-golang-goa
// --version=v1.1.0-dirty

package app

// Todo media type (default view)
//
// Identifier: application/vnd.todo+json; view=default
type Todo struct {
	// Whether the task is completed or not
	Completed *bool `form:"completed,omitempty" json:"completed,omitempty" xml:"completed,omitempty"`
	// Unique ID
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Order or priority of the task
	Order *int `form:"order,omitempty" json:"order,omitempty" xml:"order,omitempty"`
	// Title of the task
	Title *string `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
	// Link to the task
	URL *string `form:"url,omitempty" json:"url,omitempty" xml:"url,omitempty"`
}
